image: docker:git

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  SERVER_SSH: 178.128.197.67
before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - production

deploy:
  stage: deploy
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval "$(ssh-agent -s)" # start SSH agent in background
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$CREDENTIALS_KEY" | ssh-add - > ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - scp -r ./docker-compose.yml root@${SERVER_SSH}:~/
    - ssh root@$SERVER_SSH "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker pull $IMAGE_NAME; CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME docker-compose -f docker-compose.yml up -d"
  only:
    - production
